In [28]:
import numpy


def inv(matriz):
  #Matriz identidad
  tamano = numpy.shape(matriz)
  n = tamano[0]
  identidad = numpy.identity(n)

  AB = numpy.concatenate((matriz,identidad),axis=1)
  AB0 = numpy.copy(AB)

  #Pivoteo
  tamano = numpy.shape(AB)
  n = tamano[0]
  m = tamano[1]

  #Para filas en AB
  for i in range(0,n-1,1):
      #Columna desde diagonal i en adelante
      columna = abs(AB[i:,i])
      dondemax = numpy.argmax(columna)
      
      # dondemax no está en diagonal
      if (dondemax !=0):
          #Intercambia filas
          temporal = numpy.copy(AB[i,:])
          AB[i,:] = AB[dondemax+i,:]
          AB[dondemax+i,:] = temporal
  AB1 = numpy.copy(AB)

  # eliminacion hacia adelante
  for i in range(0,n-1,1):
      pivote = AB[i,i]
      adelante = i+1
      for k in range(adelante,n,1):
          factor = AB[k,i]/pivote
          AB[k,:] = AB[k,:] - AB[i,:]*factor
  AB2 = numpy.copy(AB)

  # elimina hacia atras
  ultfila = n-1
  ultcolumna = m-1
  for i in range(ultfila,0-1,-1):
      pivote = AB[i,i]
      atras = i-1 
      for k in range(atras,0-1,-1):
          factor = AB[k,i]/pivote
          AB[k,:] = AB[k,:] - AB[i,:]*factor
      # diagonal a unos
      AB[i,:] = AB[i,:]/AB[i,i]

  inversa = numpy.copy(AB[:,n:])


  print("Matriz aumentada:")
  print(AB0)
  print("Pivoteo parcial por filas")
  print(AB1)
  print('eliminacion hacia adelante')
  print(AB2)
  print('eliminación hacia atrás')
  print(AB)
  print("Inversa de la matriz: ")
  print(inversa)

In [29]:
A = numpy.array([[3,2,2],
                [3,1,-3],
                [1,0,-2]], dtype=float)

inv(A)

Matriz aumentada:
[[ 3.  2.  2.  1.  0.  0.]
 [ 3.  1. -3.  0.  1.  0.]
 [ 1.  0. -2.  0.  0.  1.]]
Pivoteo parcial por filas
[[ 3.  2.  2.  1.  0.  0.]
 [ 3.  1. -3.  0.  1.  0.]
 [ 1.  0. -2.  0.  0.  1.]]
eliminacion hacia adelante
[[ 3.          2.          2.          1.          0.          0.        ]
 [ 0.         -1.         -5.         -1.          1.          0.        ]
 [ 0.          0.          0.66666667  0.33333333 -0.66666667  1.        ]]
eliminación hacia atrás
[[ 1.   0.   0.   1.  -2.   4. ]
 [-0.   1.  -0.  -1.5  4.  -7.5]
 [ 0.   0.   1.   0.5 -1.   1.5]]
Inversa de la matriz: 
[[ 1.  -2.   4. ]
 [-1.5  4.  -7.5]
 [ 0.5 -1.   1.5]]


In [30]:
B = numpy.array([[1,2,0,4],
                [2,0,-1,-2],
                [1,1,-1,0],
                [0,4,1,0]], dtype=float)

inv(B)

Matriz aumentada:
[[ 1.  2.  0.  4.  1.  0.  0.  0.]
 [ 2.  0. -1. -2.  0.  1.  0.  0.]
 [ 1.  1. -1.  0.  0.  0.  1.  0.]
 [ 0.  4.  1.  0.  0.  0.  0.  1.]]
Pivoteo parcial por filas
[[ 2.  0. -1. -2.  0.  1.  0.  0.]
 [ 0.  4.  1.  0.  0.  0.  0.  1.]
 [ 1.  1. -1.  0.  0.  0.  1.  0.]
 [ 1.  2.  0.  4.  1.  0.  0.  0.]]
eliminacion hacia adelante
[[ 2.    0.   -1.   -2.    0.    1.    0.    0.  ]
 [ 0.    4.    1.    0.    0.    0.    0.    1.  ]
 [ 0.    0.   -0.75  1.    0.   -0.5   1.   -0.25]
 [ 0.    0.    0.    5.    1.   -0.5   0.   -0.5 ]]
eliminación hacia atrás
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   3.33333333e-01  6.66666667e-01 -6.66666667e-01 -1.38777878e-17]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00  0.00000000e+00
  -6.66666667e-02 -1.33333333e-01  3.33333333e-01  2.00000000e-01]
 [-0.00000000e+00 -0.00000000e+00  1.00000000e+00 -0.00000000e+00
   2.66666667e-01  5.33333333e-01 -1.33333333e+00  2.00000000e-01]
 [ 0.00000000e+00  